# Generated by Django 4.2.16 on 2025-11-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BereshtMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='Title (Persian)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('subtitle_fa', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtitle (Persian)')),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtitle (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('menu_type', models.CharField(choices=[('main', 'Main Menu'), ('today', "Today's Specials"), ('seasonal', 'Seasonal Menu'), ('promotional', 'Promotional Menu')], default='main', max_length=20, verbose_name='Menu Type')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='menu_covers/%Y/%m/%d/', verbose_name='Menu Cover Image')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
            ],
            options={
                'verbose_name': 'Beresht Menu',
                'verbose_name_plural': 'Beresht Menus',
                'db_table': 'beresht_menu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BereshtMenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='Section Title (Persian)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Section Title (English)')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='Description (Persian)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (English)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('beverages', 'Beverages'), ('food', 'Food Items'), ('desserts', 'Desserts'), ('specials', 'Specials')], default='beverages', max_length=50, verbose_name='Section Type')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='miyanBeresht.bereshtmenu', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'Beresht Menu Section',
                'verbose_name_plural': 'Beresht Menu Sections',
                'db_table': 'beresht_menu_section',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BereshtMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=255, verbose_name='Item Name (Persian)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Item Name (English)')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='Description (Persian)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (English)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in the base currency', max_digits=32, verbose_name='Price')),
                ('price_fa', models.CharField(help_text='Formatted price for display in Persian', max_length=50, verbose_name='Formatted Price (Persian)')),
                ('price_en', models.CharField(blank=True, help_text='Formatted price for display in English', max_length=50, verbose_name='Formatted Price (English)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/%Y/%m/%d/', verbose_name='Item Image')),
                ('image_url', models.URLField(blank=True, help_text='Alternative to uploaded image', null=True, verbose_name='External Image URL')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('is_todays_special', models.BooleanField(default=False, verbose_name="Today's Special")),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Item')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vegetarian')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Vegan')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Gluten Free')),
                ('contains_allergens', models.CharField(blank=True, help_text='Comma-separated list of allergens', max_length=500, verbose_name='Contains Allergens')),
                ('preparation_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Preparation Time (minutes)')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calories')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('espresso', 'Espresso Based'), ('milk', 'Milk Based'), ('filter', 'Filter Coffee'), ('tea', 'Tea & Infusions'), ('specialty', 'Specialty Drinks'), ('food', 'Food Items'), ('dessert', 'Desserts')], default='espresso', max_length=20, verbose_name='Item Type')),
                ('ingredients_fa', models.TextField(blank=True, null=True, verbose_name='Ingredients (Persian)')),
                ('ingredients_en', models.TextField(blank=True, null=True, verbose_name='Ingredients (English)')),
                ('available_sizes', models.CharField(blank=True, help_text='Comma-separated sizes (e.g., Small,Medium,Large)', max_length=200, verbose_name='Available Sizes')),
                ('spice_level', models.PositiveIntegerField(default=0, help_text='0-5, where 0 is not spicy and 5 is very spicy', verbose_name='Spice Level')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='miyanBeresht.bereshtmenusection', verbose_name='Menu Section')),
            ],
            options={
                'verbose_name': 'Beresht Menu Item',
                'verbose_name_plural': 'Beresht Menu Items',
                'db_table': 'beresht_menu_item',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
