# Generated by Django 4.2.16 on 2025-12-17 17:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miyanGroup', '0002_seed_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(max_length=32)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'verbose_name': 'Basic Item',
                'verbose_name_plural': 'Basic Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('basic', 'Basic Item'), ('recipe', 'Recipe')], max_length=16)),
                ('mode', models.CharField(choices=[('set', 'Set'), ('delta', 'Delta')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stock_before', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock_after', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('basic_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='inventory.basicitem')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='miyanGroup.branch')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='inventory.recipe')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to='miyanGroup.staff')),
            ],
            options={
                'verbose_name': 'Inventory Adjustment',
                'verbose_name_plural': 'Inventory Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchRecipeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_stocks', to='miyanGroup.branch')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='inventory.recipe')),
            ],
            options={
                'verbose_name': 'Branch Recipe Stock',
                'verbose_name_plural': 'Branch Recipe Stock',
                'ordering': ['branch__name', 'recipe__name'],
            },
        ),
        migrations.CreateModel(
            name='BranchBasicItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_item_stocks', to='miyanGroup.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='inventory.basicitem')),
            ],
            options={
                'verbose_name': 'Branch Basic Item Stock',
                'verbose_name_plural': 'Branch Basic Item Stock',
                'ordering': ['branch__name', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, help_text='Amount of the basic item used per recipe unit (in the same unit as the BasicItem).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('basic_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='inventory.basicitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
                'ordering': ['recipe__name', 'basic_item__name'],
                'unique_together': {('recipe', 'basic_item')},
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('basic_item__isnull', False), ('item_type', 'basic'), ('recipe__isnull', True)), models.Q(('basic_item__isnull', True), ('item_type', 'recipe'), ('recipe__isnull', False)), _connector='OR'), name='inventory_adjustment_basic_item_matches_type'),
        ),
        migrations.AlterUniqueTogether(
            name='branchrecipestock',
            unique_together={('branch', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='branchbasicitemstock',
            unique_together={('branch', 'item')},
        ),
    ]
